services:
  nuxt:
    container_name: ${PROJECT_NAME}-nuxt
    image: ${PROJECT_NAME}-nuxt:${PROJECT_NAME}-${PROJECT_VERSION}
    build:
      context: .
      dockerfile: ${NUXT_DOCKERFILE}/Dockerfile
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"
    environment:
      NUXT_PORT: ${NUXT_PORT}
      EXPRESS_PORT: ${EXPRESS_PORT}
    volumes:
      - ${NUXT_DIRECTORY}:${NUXT_WORK_DIRECTORY}
    working_dir: ${NUXT_WORK_DIRECTORY}
    command: sh -c "npm install && npm run dev"
    depends_on:
      - express

  express:
    container_name: ${PROJECT_NAME}-express
    image: ${PROJECT_NAME}-express:${PROJECT_NAME}-${PROJECT_VERSION}
    build:
      context: .
      dockerfile: ${EXPRESS_DOCKERFILE}/Dockerfile
    volumes:
      - ${EXPRESS_DIRECTORY}:${EXPRESS_WORK_DIRECTORY}
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      EXPRESS_PORT: ${EXPRESS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    working_dir: ${EXPRESS_WORK_DIRECTORY}
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mysql

  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: ${PROJECT_NAME}-mysql:${PROJECT_NAME}-${PROJECT_VERSION}
    build:
      context: .
      dockerfile: ${MYSQL_DOCKERFILE}/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: ${PROJECT_NAME}-phpmyadmin:${PROJECT_NAME}-${PROJECT_VERSION}
    build:
      context: .
      dockerfile: ${PHPMYADMIN_DOCKERFILE}/Dockerfile
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${PHPMYADMIN_USERNAME}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    volumes:
      - phpmyadmin:/sessions
    depends_on:
      - mysql

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: ${PROJECT_NAME}-redis:${PROJECT_NAME}-${PROJECT_VERSION}
    build:
      context: .
      dockerfile: ${REDIS_DOCKERFILE}/Dockerfile
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data

volumes:
  mysql:
    name: ${PROJECT_NAME}-mysql
    driver: local
  phpmyadmin:
    name: ${PROJECT_NAME}-phpmyadmin
    driver: local
  redis:
    name: ${PROJECT_NAME}-redis
    driver: local
